export const AFFECTS = [
  'Self-esteem',
  'Security',
  'Ambitions',
  'Personal relations',
  'Sex relations',
  'Pride',
  'Finances',
  'Emotional security',
];

export const DEFECTS = [
  'Anger',
  'Fear',
  'Dishonesty',
  'Selfishness',
  'Jealousy',
  'Resentment',
  'People-pleasing',
  'Control',
  'Perfectionism',
  'Blaming',
  'Avoidance',
  'Entitlement',
  'Judgment',
  'Pride',
  'Dishonor',
  'Self-pity',
];

export const ASSETS = [
  'Honesty',
  'Humility',
  'Courage',
  'Compassion',
  'Patience',
  'Accountability',
  'Willingness',
  'Gratitude',
  'Acceptance',
  'Forgiveness',
  'Service',
  'Open-mindedness',
  'Self-care',
  'Boundaries',
  'Faith',
  'Calm',
];

export const DEFECT_TO_ASSET: Record<string, string> = {
  Anger: 'Calm',
  Fear: 'Courage',
  Dishonesty: 'Honesty',
  Selfishness: 'Service',
  Jealousy: 'Gratitude',
  Resentment: 'Forgiveness',
  'People-pleasing': 'Boundaries',
  Control: 'Acceptance',
  Perfectionism: 'Humility',
  Blaming: 'Accountability',
  Avoidance: 'Willingness',
  Entitlement: 'Humility',
  Judgment: 'Compassion',
  Pride: 'Humility',
  Dishonor: 'Honesty',
  'Self-pity': 'Gratitude',
};

export type HelperType = 'affects' | 'defects' | 'assets';

export const HELPER_CONTENT: Record<HelperType, { label: string; description: string }[]> = {
  affects: [
    { label: 'Self-esteem', description: 'What I think of myself.' },
    { label: 'Pride', description: 'What I think others think of me.' },
    { label: 'Security', description: 'My sense of safety and stability.' },
    { label: 'Ambitions', description: 'My goals, plans, and aspirations.' },
    { label: 'Personal relations', description: 'Friendships, family ties, and close relationships.' },
    { label: 'Sex relations', description: 'Intimacy, attraction, and sexual relationships.' },
    { label: 'Finances', description: 'Money, spending, and financial well-being.' },
    { label: 'Emotional security', description: 'My emotional safety, calm, and balance.' },
  ],
  defects: [
    { label: 'Anger', description: 'I respond with hostility or resentment.' },
    { label: 'Fear', description: 'I act from worry, insecurity, or dread.' },
    { label: 'Dishonesty', description: 'I hide, distort, or avoid the truth.' },
    { label: 'Selfishness', description: 'I put my wants above others consistently.' },
    { label: 'Jealousy', description: 'I compare and feel threatened by others.' },
    { label: 'Resentment', description: 'I hold on to anger or grievances.' },
    { label: 'People-pleasing', description: 'I seek approval at my own expense.' },
    { label: 'Control', description: 'I try to manage people or outcomes.' },
    { label: 'Perfectionism', description: 'I demand unrealistic standards.' },
    { label: 'Blaming', description: 'I avoid responsibility by faulting others.' },
    { label: 'Avoidance', description: 'I escape or delay hard things.' },
    { label: 'Entitlement', description: 'I expect special treatment or exceptions.' },
    { label: 'Judgment', description: 'I criticize or condemn quickly.' },
    { label: 'Pride', description: 'I elevate myself or need admiration.' },
    { label: 'Dishonor', description: 'I act against my values or integrity.' },
    { label: 'Self-pity', description: 'I dwell on how unfair things are to me.' },
  ],
  assets: [
    { label: 'Honesty', description: 'I tell the truth and act with integrity.' },
    { label: 'Humility', description: 'I stay teachable and grounded.' },
    { label: 'Courage', description: 'I face fears and do the right thing.' },
    { label: 'Compassion', description: 'I show care and understanding.' },
    { label: 'Patience', description: 'I endure delays without frustration.' },
    { label: 'Accountability', description: 'I own my actions and choices.' },
    { label: 'Willingness', description: 'I am open to change and guidance.' },
    { label: 'Gratitude', description: 'I focus on what I have and appreciate.' },
    { label: 'Acceptance', description: 'I allow reality as it is.' },
    { label: 'Forgiveness', description: 'I release resentment and move forward.' },
    { label: 'Service', description: 'I put others needs before my ego.' },
    { label: 'Open-mindedness', description: 'I consider new ideas and perspectives.' },
    { label: 'Self-care', description: 'I care for my health and well-being.' },
    { label: 'Boundaries', description: 'I set healthy limits with others.' },
    { label: 'Faith', description: 'I trust guidance beyond myself.' },
    { label: 'Calm', description: 'I respond with steadiness and peace.' },
  ],
};
